### ISSUE TITLE
Cloudflareに招待する

### ISSUE THREAD

**Issue by haton14** [coniva-bouldering/bouldering-gym-notifier#1]

**Comment by haton14** [comment]
とりあえず自分のサブアカウントを招待してみて権限がどうなるのか見てみる

**Comment by haton14** [comment]
https://github.com/coniva-bouldering/bouldering-gym-notifier/issues/12

検証してみた

**Comment by haton14** [comment]
メアドを @tsuna-can に聞き中

**Comment by haton14** [comment]
ちなみにメアドをオープンにしてよいなら、こんな感じでGitHub上で表示できるように設定できるよ！
![スクリーンショット 2023-04-07 203425](https://user-images.githubusercontent.com/75571105/230602464-9a99c2fc-e7c4-4847-90e2-83e3528027e4.png)

**Comment by haton14** [comment]
![スクリーンショット 2023-04-07 203935](https://user-images.githubusercontent.com/75571105/230603195-492d5182-e373-49b5-b1d3-734b8d1d41de.png)

@tsuna-can 
2FA強制で招待した！

**Comment by tsuna-can** [comment]
@haton14 
参加しました！

**Comment by haton14** [comment]
@tsuna-can 
✔
