### ISSUE TITLE
CDの作成

### ISSUE THREAD

**Issue by haton14** [coniva-bouldering/bouldering-gym-notifier#11]

**Comment by tsuna-can** [comment]
- cronにCD追加
- webhookにCD追加

**Comment by tsuna-can** [comment]
すいません見逃してました！
やってみます

**Comment by haton14** [comment]
wranglerもv3にあげた方が良さげ！！
その際にコマンドが変わってる可能性高いかも？

**Comment by haton14** [comment]
ちな今の状況

5月頭
→新しい職場に慣れるので心身疲弊

今
→ティアキン忙しくてやる気消失

**Comment by tsuna-can** [comment]
@haton14 
とりあえずできたところまでdraftにしました！->  [PR](https://github.com/coniva-bouldering/bouldering-gym-notifier/pull/93)
このrepo上での開発ブランチを使った動作確認方法がわからないです 😢

**Comment by tsuna-can** [comment]
webhookのCDはこっちで対応
https://github.com/coniva-bouldering/bouldering-gym-notifier/issues/97
