### ISSUE TITLE
フレームワークを使用するか検討する

### ISSUE THREAD

**Issue by haton14** [coniva-bouldering/bouldering-gym-notifier#3]

**Comment by haton14** [comment]
@tsuna-can 
今回はUIないので使用するフレームワークは以下でよいかも

- https://superflare.dev/

- https://hono.dev/

- 純粋なNodeの関数のみ

**Comment by tsuna-can** [comment]
Star数的にはhonoですね

**Comment by haton14** [comment]
どっちもWeb APIとしてのフレームワークな気がするから、定期的にバッチ的に起動してスクレイピングしてもらう用途だと要らないかも？

https://qiita.com/donraq/items/6d1d9d0a2a02dde09fb8


wranglerでプロジェクトとテンプレ作成して、オプション付けて実行すればローカル起動するのでとりあえずこれで進めるで良さげかもしれん
https://yusukebe.com/posts/2022/wrangler2/

**Comment by haton14** [comment]
ただのワーカーとしての用途でもフレームワークのドキュメント見て使う例あったら採用はもちろんあり

isuue含めて適当に検索してもなさげなら完了にしちゃっていいわよ

**Comment by tsuna-can** [comment]
基本APIとしての用途っぽいですね
とりあえずフレームワーク使わずにやってみようと思います

**Comment by haton14** [comment]
💯 1
