### ISSUE TITLE
ボルダリングジムの最新記事3件取得して、結果をログ出力する機能の実装

### ISSUE THREAD

**Issue by haton14** [coniva-bouldering/bouldering-gym-notifier#6]
# 概要
- [ ] 後ほど対象となるジムが増えたときにスクレイピングを分けたいので、ジム毎にファイルかディレクトリを分割するようにする
  - 今回の対象: https://pump-climbing.com/gym/akiba/news/

# 留意点
- Cloudflare Workersってログは外部に逃さないと残らなかった気もする
  - 失敗したときはログ残すようにしたいから何か方法考えなきゃ。。。
  - Sentryとか有名だけど無料枠あるんかな
  - R2使えば良さそう！！
    - https://dev.classmethod.jp/articles/cloudflare-r2-logpush/

**Comment by haton14** [comment]
@tsuna-can 
まかせた！

**Comment by haton14** [comment]
ライブラリ使う場合はworkersのエンジンはv8(ブラウザと同じ)なので注意

https://dev.classmethod.jp/articles/remix-on-cloudflare-workers/

**Comment by tsuna-can** [comment]
スクレイピングに使うライブラリを検討する

**Comment by haton14** [comment]
そういえば共有してなかったので！

CPU時間10ms
ビルド後のスクリプトサイズ1MB
とかの制限あるけど、お試しでデプロイしてダメそうだったら適当にAWSのLambdaとかに乗り換えるつもり

**Comment by tsuna-can** [comment]
スクレイピングのライブラリの有名どころ(Node.js用なので使えるのか不明)

- Puppeteer
- JSDOM
- Cheerio

Cloudflare用にだれかが作ったやつ?
- https://github.com/JimmyLaurent/cloudflare-scraper

**Comment by tsuna-can** [comment]
HTMLの解析に使えるかも
https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/

**Comment by haton14** [comment]
記事タイトルとリンクさえ取れれば良いのでシンプルなやつが良さげかも！(詳細は見れてない)

**Comment by tsuna-can** [comment]
一旦なんも使わずにやってみようと思います

**Comment by tsuna-can** [comment]
ライブラリ使わなくても正規表現でできました

**Comment by tsuna-can** [comment]
R2について調べる

**Comment by haton14** [comment]
素晴らしい！！！

**Comment by tsuna-can** [comment]
@haton14 
感謝

**Comment by haton14** [comment]
@tsuna-can 
早速セキュリティ対策のPRめっちゃきたのでpull後にrebase mainして最新のを取り込んだ方がよいかも。
多分やらないとコンフリクトする。
![スクリーンショット 2023-04-11 18 24 07](https://user-images.githubusercontent.com/75571105/231116608-aa00335a-faab-4c3a-bcc5-ebc98827e57d.png)

**Comment by tsuna-can** [comment]
@haton14 
R2のログの書き込みよくわかりません 😢 

https://developers.cloudflare.com/r2/api/workers/workers-api-reference/
https://zenn.dev/kameoncloud/articles/96e27a6eba410e
https://developers.cloudflare.com/r2/api/workers/workers-api-usage/

`await env.MY_BUCKET.put(key, request.body);`で書き込めるんでしょうか？？

とりあえずスクレイピングするとこまでpushしました

**Comment by haton14** [comment]
@tsuna-can 
僕ちんも触ったことないからログ出しは別途やってみるわ！

スクレイピングするところまでをPR作成お願い！
ついでにPRのコメントでisuueとも紐付けてちょ
紐付けるワードは他のPR見れば分かると思う
