### ISSUE TITLE
記事URLをLINEに投稿する機能の実装

### ISSUE THREAD

**Issue by haton14** [coniva-bouldering/bouldering-gym-notifier#7]
## 使うAPI
https://developers.line.biz/ja/reference/messaging-api/#send-push-message

- チャネルアクセストークンはログインしたら見れる。
  - 秘匿情報なのでGitHubにプッシュしないように！
  - 環境変数経由で使う。
    - ローカルはenvファイルなどを読み込む

**Comment by haton14** [comment]
@tsuna-can 
Messaging APIの使い方見てみた感じWeb APIサーバー必要そうだわ。。
クイックスタート
https://developers.line.biz/ja/docs/messaging-api/getting-started/

プッシュメッセージを送るAPIのドキュメント
https://developers.line.biz/ja/reference/messaging-api/#send-push-message
https://developers.line.biz/ja/reference/messaging-api/#send-push-message-request-body

Webhookから取得したIDが必須！！！！
![スクリーンショット 2023-04-18 213333](https://user-images.githubusercontent.com/75571105/232778461-14e9fb2e-a14f-412d-bc4c-6065d9b61e6f.png)

Webhookについて
https://developers.line.biz/ja/docs/messaging-api/receiving-messages/

- つまりWeb APIサーバーも必要
  - workerにCronとWeb APIサーバーは共存できるのか？
    - できないとしたらD1(sqlite)にプッシュメッセージ送信先のIDを入れるためのWeb APIサーバーも別途必要
      - Honoでいいかなあ
    - 送信先IDをD1(sqlite)から取得する処理が増えるだけで、Cronでやる処理の大筋は変わらない。

**Comment by haton14** [comment]
@tsuna-can 
タスクとしては↓の２つになる

> workerにCronとWeb APIサーバーは共存できるのか

1.これの検証

> できないとしたらD1(sqlite)にプッシュメッセージ送信先のIDを入れるためのWeb APIサーバーも別途必要

2.これの実装

1をぼくちんがやって、2を @tsuna-can がやるのがやりやすいかも？

**Comment by tsuna-can** [comment]
@haton14 
調査ありがとうございます！承知です！Honoは使ってみたいと思ってました

> workerにCronとWeb APIサーバーは共存できるのか

の検証が終わってから実装を始める感じでいいですか？？

**Comment by haton14** [comment]
@tsuna-can 
せやね！

そういえばHonoの人がcloudflareに入社したらしい

https://yusukebe.com/posts/2023/join-cloudflare/

**Comment by tsuna-can** [comment]
すごい

**Comment by haton14** [comment]
@tsuna-can 
同一ワーカー上にWeb APIとCronは共存できなさげなので、それぞれ作ろう！
https://github.com/coniva-bouldering/bouldering-gym-notifier/pull/37#issuecomment-1524650441

**Comment by haton14** [comment]
@tsuna-can 
モノレポにしたいと思う
https://github.com/coniva-bouldering/bouldering-gym-notifier/pull/38

**Comment by tsuna-can** [comment]
@haton14 
検証ありがとうございます！
Web APIサーバーの実装は新しくブランチ切って開発していけばOKですか？

**Comment by haton14** [comment]
@tsuna-can 
>Web APIサーバーの実装は新しくブランチ切って開発していけばOKですか？

こっちでよし！

https://github.com/coniva-bouldering/bouldering-gym-notifier/pull/38
モノレポに対応するPRマージしたらでオナシャス。
approveしたらマージしちゃっていいよ！
モノレポなんで、プロジェクトのrootではなく、`webhook `or `notifier`い移動して作業すればヨシ

**Comment by tsuna-can** [comment]
承知です！！

**Comment by haton14** [comment]
あざ！！
honoで作ったwebhook用のAPIデプロイしちゃって、lineのコンソールに登録する必要があると思う

今時点でやることこれだろうってクソ細かい粒度でここに投稿してもらえると認識合わせしやすいかも！

**Comment by tsuna-can** [comment]
こんな感じだと思ってます！

- ディレクトリ構造に関して（いらない？）
  - 共通の package.json を作成し、packages（notifier, webhook）の追加
- webhook の受信の確認
  - Hono で API を作成してデプロイ
  - それを Line のコンソールに登録して webhook を受信できるか確認
- メッセージの投稿
  - 動作確認用の Line グループの作成
  - Line グループの groupID を確認
  - groupID を D1 に登録
  - メッセージを投稿する機能の作成
      - D1 から groupID の取得
      - プッシュメッセージを投稿する API を叩く

将来的にはフォローイベントか参加イベントを受け取って、userID、groupIDをD1に登録しておくという感じであってますか？
https://developers.line.biz/ja/reference/messaging-api/#follow-event
https://developers.line.biz/ja/reference/messaging-api/#join-event

**Comment by haton14** [comment]
@tsuna-can 
webhook受信の確認でしかgroupid受け取れない可能性あるかも！

共通のpackage.jsonは要らなくて、それぞれのディレクトリに作る方針でいこう

あとは合ってる！！！

**Comment by haton14** [comment]
正直LINEのこのドキュメントみただけじゃわからん！！(親切じゃないと思う

**Comment by tsuna-can** [comment]
@haton14 
wrangler.tomlにd1のdatabase_idとかを入れてるんですけど、これらを環境変数として設定する方法わかりますか？？
このままpushしちゃっていいんでしょうか？

```toml
[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "aaaa"
database_id = "aaaa"
```

LineのChannel_access_tokenは.dev.varsに記入する、もしくはworkersのコンソールからの設定でいけました。

**Comment by haton14** [comment]
@tsuna-can 
D1は直接パブリックアクセスできないので`wrangler.toml`に接続情報入れちゃって問題なしだわ。

**Comment by haton14** [comment]
@tsuna-can 
コメントもした！

**Comment by haton14** [comment]
機能としては満たしてるのでこのisuueは閉じてヨシ！

**Comment by tsuna-can** [comment]
https://github.com/coniva-bouldering/bouldering-gym-notifier/issues/9 で

> カラム追加した上で、タイトル+URLでDBに保存して、通知もこの形式でやるようにする

これに対応します 🐤

**Comment by haton14** [comment]
- webhookのドメイン制限

これ忘れてたわ

**Comment by haton14** [comment]
@tsuna-can 
署名の検証でいけるらしい

https://www.line-community.me/ja/question/5ac36a844016900baf7a4337

(もしかしてもう署名の検証までやってる！？？)

**Comment by tsuna-can** [comment]
@haton14 
いや、やってないです！全然知りませんでした
