### ISSUE TITLE
webhookのドメイン制限

### ISSUE THREAD

**Issue by tsuna-can** [coniva-bouldering/bouldering-gym-notifier#71]

**Comment by tsuna-can** [comment]
参考：https://www.line-community.me/ja/question/5ac36a844016900baf7a4337

**Comment by haton14** [comment]
(間違った表現してた気がするので一応)
WAFやロードバランサー、CSRFとかでドメイン制限もどきみたいなのできるけど
今回やっているのは署名を使ってちゃんとラインからきているのか検証しているだけだったわ！！
メールの署名とかとだいたい同じ
